/**
 * Compiles playbooks/*.yaml into src/playbooks-data.ts so the mobile bundle
 * carries them without a filesystem or YAML parser at runtime.
 * Regenerate after editing playbooks: node scripts/bundle-playbooks.ts
 */
import { readdirSync, writeFileSync } from "node:fs";
import { loadPlaybook } from "../src/playbook.ts";

const map: Record<string, unknown> = {};
for (const f of readdirSync("playbooks").sort()) {
  if (!f.endsWith(".yaml")) continue;
  const pb = loadPlaybook(`playbooks/${f}`);
  map[pb.id] = pb;
}

writeFileSync(
  "src/playbooks-data.ts",
  `// GENERATED by scripts/bundle-playbooks.ts — do not edit by hand.\n` +
  `import type { Playbook } from "./types.ts";\n\n` +
  `export const PLAYBOOKS: Record<string, Playbook> =\n` +
  `  ${JSON.stringify(map, null, 2).replace(/\n/g, "\n  ")} as unknown as Record<string, Playbook>;\n`,
);
console.log(`bundled ${Object.keys(map).length} playbooks → src/playbooks-data.ts`);
