// GENERATED by scripts/bundle-playbooks.ts — do not edit by hand.
import type { Playbook } from "./types.ts";

export const PLAYBOOKS: Record<string, Playbook> =
  {
    "action_recipe": {
      "id": "action_recipe",
      "version": "0.1.0",
      "kind": "derived",
      "sector": "action",
      "title": "Action recipe",
      "purpose": "Turns your success formula into concrete moves in the real world. The premise, from career construction theory: action, not decidedness, carries you forward — you learn which future you want by exploring it. The plan names two or three directions that fit your authorized artifacts, assigns each the book's information-seeking behaviors (writing, observing, reading, listening, visiting, talking), sets three first steps for the coming week, and names the barrier most likely to stall you — with its counter-move. Everything must occur in the real world, and you authorize all of it.\n",
      "consumes": [
        "identity_statement",
        "life_portrait",
        "preferred_settings",
        "counseling_goal"
      ],
      "invalidates": [
        "closing_check"
      ],
      "induce": {
        "steps": [
          {
            "id": "plan",
            "task": "From the identity statement, life portrait, and preferred settings, draft the user's exploration plan, second person. Propose two or three directions (occupations, roles, or paths) that would let the user live their formula — for each, say in one sentence why it fits their authorized artifacts (cite their own words where possible), name its exploration stage (crystallize: comparing broad options; specify: deepening one; actualize: securing a real position or trial), and give two or three concrete exploration actions drawn from the six information-seeking behaviors — writing, observing, reading, listening, visiting, talking — each naming a real-world step the user could take. Then set week_one: the three smallest concrete moves for the next seven days. Finally, from the portrait's tensions, name the single most likely barrier for THIS user (a feeling like anxiety or guilt, a practical constraint, or an unsupportive audience) and give one gentle counter-move; if the barrier is a feeling, name it kindly. No generic advice: every item must trace back to the user's artifacts.\n",
            "model_tier": "large",
            "output_schema": {
              "type": "object",
              "required": [
                "directions",
                "week_one",
                "barrier"
              ],
              "properties": {
                "directions": {
                  "type": "array",
                  "minItems": 2,
                  "maxItems": 3,
                  "items": {
                    "type": "object",
                    "required": [
                      "name",
                      "why_it_fits",
                      "stage",
                      "actions"
                    ],
                    "properties": {
                      "name": {
                        "type": "string"
                      },
                      "why_it_fits": {
                        "type": "string"
                      },
                      "stage": {
                        "type": "string",
                        "enum": [
                          "crystallize",
                          "specify",
                          "actualize"
                        ]
                      },
                      "actions": {
                        "type": "array",
                        "minItems": 2,
                        "maxItems": 3,
                        "items": {
                          "type": "object",
                          "required": [
                            "behavior",
                            "step"
                          ],
                          "properties": {
                            "behavior": {
                              "type": "string",
                              "enum": [
                                "writing",
                                "observing",
                                "reading",
                                "listening",
                                "visiting",
                                "talking"
                              ]
                            },
                            "step": {
                              "type": "string"
                            }
                          }
                        }
                      }
                    }
                  }
                },
                "week_one": {
                  "type": "array",
                  "minItems": 3,
                  "maxItems": 3,
                  "items": {
                    "type": "string"
                  }
                },
                "barrier": {
                  "type": "object",
                  "required": [
                    "name",
                    "counter_move"
                  ],
                  "properties": {
                    "name": {
                      "type": "string"
                    },
                    "counter_move": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        ]
      },
      "confirm": {
        "present": "structured_review",
        "authorize_language": "This plan only counts if it happens in the real world — trim anything you won't actually do, and make the first steps embarrassingly small. When you've explored, come back for the closing check.\n"
      },
      "artifact": {
        "schema": {
          "type": "object",
          "required": [
            "directions",
            "week_one",
            "barrier"
          ],
          "properties": {
            "directions": {
              "type": "array"
            },
            "week_one": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "barrier": {
              "type": "object"
            }
          }
        },
        "render": "{{#each week_one}}• {{this}}\n{{/each}}\n"
      },
      "gate": "all"
    },
    "advice_to_self": {
      "id": "advice_to_self",
      "version": "0.1.0",
      "kind": "derived",
      "sector": "induction",
      "title": "Advice to self",
      "purpose": "Unpacks your motto into the call to action it already contains. The premise, from career construction theory: a favorite saying is autotherapy — the best advice you have for yourself, usually stating your own strategy for moving to the next chapter. The answers you seek were already in your pocket; this step just says so plainly. Your motto stays word-for-word yours, and it will be handed back to you at the very end of the journey.\n",
      "consumes": [
        "motto",
        "counseling_goal"
      ],
      "invalidates": [
        "life_portrait"
      ],
      "induce": {
        "steps": [
          {
            "id": "unpack",
            "task": "Take the motto exactly as recorded and unfold the advice it contains, addressed to the user in the second person. Connect it directly to the request in the counseling goal: how does this saying answer the very thing the user came here for? State the concrete move the motto is telling the user to make next. Do not improve, correct, or replace the motto — the wisdom must remain the user's own, only made explicit.\n",
            "model_tier": "small",
            "output_schema": {
              "type": "object",
              "required": [
                "motto",
                "call_to_action",
                "answers_the_request"
              ],
              "properties": {
                "motto": {
                  "type": "string",
                  "x-verbatim": true,
                  "description": "The saying, exactly as the user recorded it."
                },
                "call_to_action": {
                  "type": "string",
                  "description": "Two or three second-person sentences — the move the motto is already advising."
                },
                "answers_the_request": {
                  "type": "string",
                  "description": "One or two sentences connecting the motto to the user's stated goal."
                }
              }
            }
          }
        ]
      },
      "confirm": {
        "present": "structured_review",
        "authorize_language": "This is your own advice, said back to you plainly — adjust anything that doesn't sound like what you meant. The life portrait builds on what you approve here.\n"
      },
      "artifact": {
        "schema": {
          "type": "object",
          "required": [
            "motto",
            "call_to_action"
          ],
          "properties": {
            "motto": {
              "type": "string"
            },
            "call_to_action": {
              "type": "string"
            },
            "answers_the_request": {
              "type": "string"
            }
          }
        },
        "render": "“{{motto}}” — {{call_to_action}}\n"
      }
    },
    "character_sketch": {
      "id": "character_sketch",
      "version": "0.1.0",
      "kind": "derived",
      "sector": "induction",
      "title": "Character sketch",
      "purpose": "Composes a short portrait of who you are — built only from the words you approved in the role models step. The premise, from career construction theory: the traits you admired in your childhood models are the blueprint you used to build yourself, and they exist as your solution to what preoccupied you early on (bravery exists to solve fear). When your perspective artifact is available, the sketch is framed that way. Nothing is invented here: every trait must be a quote of your own words, and you edit and authorize the result.\n",
      "consumes": [
        "role_models",
        "perspective",
        "counseling_goal"
      ],
      "invalidates": [
        "script",
        "life_portrait"
      ],
      "induce": {
        "steps": [
          {
            "id": "sketch",
            "task": "Compose a second-person character sketch of four to eight sentences, addressed to the user (\"You are…\"), from the role_models artifact. Anchor it on the primacy trait (weight it most) and the repeated traits. Quote the user's descriptor words rather than substituting synonyms. Show with concrete phrasing instead of abstract labels. If a perspective artifact is present, frame the traits as the solution the user constructed to the preoccupation it names — the way bravery solves fear. If two traits sit in tension, keep the tension visible rather than smoothing it over. Name explicitly how the anchor trait may also work against the user in their present situation — the admired strength read honestly as the very thing that can keep them stuck. Never add a trait the user did not state.\n",
            "model_tier": "large",
            "output_schema": {
              "type": "object",
              "required": [
                "sketch",
                "core_traits",
                "solves"
              ],
              "properties": {
                "sketch": {
                  "type": "string",
                  "description": "The portrait prose, second person."
                },
                "core_traits": {
                  "type": "array",
                  "minItems": 2,
                  "items": {
                    "type": "string",
                    "x-verbatim": true
                  },
                  "description": "The trait words the sketch is built on, quoted exactly."
                },
                "solves": {
                  "type": [
                    "string",
                    "null"
                  ],
                  "description": "The preoccupation these traits answer, when the perspective artifact is available; otherwise null."
                }
              }
            }
          }
        ]
      },
      "confirm": {
        "present": "structured_review",
        "authorize_language": "This sketch is assembled only from your own words. Reword anything that doesn't sound like you — the script and the life portrait will build on what you approve here.\n"
      },
      "artifact": {
        "schema": {
          "type": "object",
          "required": [
            "sketch",
            "core_traits"
          ],
          "properties": {
            "sketch": {
              "type": "string"
            },
            "core_traits": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "solves": {
              "type": [
                "string",
                "null"
              ]
            }
          }
        },
        "render": "{{sketch}}\n"
      }
    },
    "closing_check": {
      "id": "closing_check",
      "version": "0.1.0",
      "kind": "conversation",
      "sector": "action",
      "title": "Closing check",
      "purpose": "The closing ritual, straight from the book. Your original request is read back to you word for word, and you — no one else — judge whether it was met. Then you name what's different now, because saying the change out loud is what makes it stick. And at the very end, your own motto is handed back to you: the advice you carried all along, now with a journey behind it. This step records your verdict; it changes nothing else.\n",
      "consumes": [
        "counseling_goal",
        "action_recipe",
        "motto"
      ],
      "invalidates": [],
      "elicit": {
        "share_upstream": true,
        "persona": "Warm, unhurried, celebratory without flattery. This is a ritual of\nclosure, not another interview. One question at a time. When quoting the\nuser's request or motto from the artifacts, quote them exactly, word for\nword — never paraphrase them.\n",
        "guardrails": [
          "The user is the only judge of whether their request was met. Accept \"partly\" and \"no\" with full respect and without defending the process.",
          "Quote the counseling_goal request_verbatim and the motto exactly as they appear in the artifacts. Never edit, shorten, or improve them.",
          "Do not open new counseling topics; if something big surfaces, note warmly that the map can be revisited any time."
        ],
        "stages": [
          {
            "id": "verdict",
            "goal": "The user's own judgment on whether their original request was met.",
            "opening": "We've reached the end of the map. Ready to check the journey against where you started?\n",
            "opening_i18n": {
              "ru": "Мы дошли до конца карты. Готов сверить путь с тем, с чего ты начинал?\n"
            },
            "probes": [
              {
                "when": "the user is ready",
                "then": "Read their original request back word for word from the counseling_goal artifact, then ask — did we get there?"
              },
              {
                "when": "the verdict is \"partly\" or \"no\"",
                "then": "Ask what remains unanswered, and note which checkpoint on the map speaks to it — revisiting is how this process is meant to work."
              }
            ],
            "done_when": [
              "The user has given a verdict on their original request — met, partly, or not."
            ]
          },
          {
            "id": "difference",
            "goal": "The change, said in the user's own words.",
            "opening": "And compared with the day you first answered that question — what's different now?\n",
            "probes": [
              {
                "when": "the user answers abstractly",
                "then": "Ask what they now do, or are about to do, that they weren't doing before."
              }
            ],
            "done_when": [
              "The user has named at least one concrete difference."
            ]
          },
          {
            "id": "sendoff",
            "goal": "Hand the motto back and close.",
            "opening": "One last thing before you go.\n",
            "probes": [
              {
                "when": "opening the send-off",
                "then": "Tell the user they had the answer with them all along, quote their motto word for word from the motto artifact, and wish them well on the next chapter — briefly and warmly."
              }
            ],
            "done_when": [
              "The user has responded to the send-off in any way."
            ]
          }
        ]
      },
      "induce": {
        "steps": [
          {
            "id": "record",
            "task": "Record the closing verdict from the conversation. Quote the user's own words for the verdict and the difference they named.\n",
            "model_tier": "small",
            "output_schema": {
              "type": "object",
              "required": [
                "goal_met",
                "verdict_words",
                "whats_different"
              ],
              "properties": {
                "goal_met": {
                  "type": "string",
                  "enum": [
                    "yes",
                    "partly",
                    "no"
                  ]
                },
                "verdict_words": {
                  "type": "array",
                  "minItems": 1,
                  "items": {
                    "type": "string",
                    "x-verbatim": true
                  }
                },
                "whats_different": {
                  "type": "array",
                  "minItems": 1,
                  "items": {
                    "type": "string",
                    "x-verbatim": true
                  }
                },
                "remaining": {
                  "type": [
                    "string",
                    "null"
                  ],
                  "description": "What still feels unanswered, if the user said so; null otherwise."
                }
              }
            }
          }
        ]
      },
      "confirm": {
        "present": "structured_review",
        "authorize_language": "The journey is yours, and so is this record of it. The map stays open — any checkpoint can be revisited, and your goal can be amended for a new round whenever life asks for one.\n"
      },
      "artifact": {
        "schema": {
          "type": "object",
          "required": [
            "goal_met",
            "verdict_words",
            "whats_different"
          ],
          "properties": {
            "goal_met": {
              "type": "string"
            },
            "verdict_words": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "whats_different": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "remaining": {
              "type": [
                "string",
                "null"
              ]
            }
          }
        },
        "render": "{{goal_met}} — {{#each whats_different}}{{this}}; {{/each}}\n"
      }
    },
    "counseling_goal": {
      "id": "counseling_goal",
      "version": "0.1.0",
      "kind": "conversation",
      "sector": "goal",
      "title": "Counseling goal",
      "purpose": "Establish, in your own words, what you want from this whole process. Your answer becomes the lens for every later step, and at the very end it is read back to you to ask: did we get there? Nothing is analyzed here beyond restating what you said, and you approve the restatement. You can amend the goal later — your original wording is always kept for that final check.\n",
      "consumes": [],
      "invalidates": [
        "perspective",
        "character_sketch",
        "preferred_settings",
        "script",
        "advice_to_self",
        "life_portrait",
        "identity_statement",
        "action_recipe"
      ],
      "amendable_after": "life_portrait",
      "elicit": {
        "persona": "You are a career construction interviewer opening a consultation. Warm, brief,\nunhurried. Ask one question at a time. In this phase you never analyze,\ndiagnose, or advise. When you reflect something back, use the user's own words.\n",
        "guardrails": [
          "Never propose or suggest goals; only ask and reflect.",
          "If the user asks for a test or personality assessment, explain in one sentence that this process works through their own stories instead, then return to the question.",
          "Listen for the request behind the request, and ask about it — but the user decides what their goal is. Do not overrule their framing.",
          "If the user expresses acute distress or mentions self-harm, acknowledge with care, provide crisis resources, and pause the interview."
        ],
        "stages": [
          {
            "id": "open",
            "goal": "Capture the request in the user's own words.",
            "opening": "How can this process be useful to you as you construct your career?\n",
            "opening_i18n": {
              "ru": "Чем этот процесс может быть полезен тебе в построении твоей карьеры?\n"
            },
            "probes": [
              {
                "when": "the answer is a single broad phrase (\"figure things out\", \"career change\", \"find my path\")",
                "then": "Ask what would make this genuinely worth their time."
              },
              {
                "when": "several distinct requests appear",
                "then": "Reflect the list back in their words and ask which matters most right now."
              },
              {
                "when": "the request is about making a decision",
                "then": "Ask gently whether the hard part is making the choice, or understanding what is blocking the choice. Clients who ask for help choosing often actually want to know what holds them back."
              },
              {
                "when": "the request sounds like confirming a decision already made",
                "then": "Ask what kind of reassurance would help, and from whom."
              }
            ],
            "done_when": [
              "The user has stated a request in at least one full sentence."
            ]
          },
          {
            "id": "success",
            "goal": "Elicit at least one concrete success criterion.",
            "opening": "Imagine we finish and it was worth it. What are you walking away with?\n",
            "probes": [
              {
                "when": "the answer restates the goal abstractly",
                "then": "Ask what they would do differently the following week if this worked."
              }
            ],
            "done_when": [
              "At least one concrete success criterion has been stated."
            ]
          },
          {
            "id": "wrap",
            "goal": "Reflect and close.",
            "opening": "Reflect the request and success criteria back in the user's own words and ask whether anything is missing.\n",
            "done_when": [
              "The user has confirmed the reflection or finished adding to it."
            ]
          }
        ]
      },
      "induce": {
        "steps": [
          {
            "id": "extract",
            "task": "Extract the goal fields from the transcript with strict field discipline: request_verbatim is the user's answer to the OPENING question — the request exactly as first stated, never a later restatement and never the success answer; success_criteria come only from the answers about what would make the process worth it; feelings_mentioned holds only the emotion words the user actually used (a whole sentence is not a feeling). When unsure which field a quote belongs to, follow the order of the conversation.\n",
            "model_tier": "small",
            "temperature": 0.2,
            "output_schema": {
              "type": "object",
              "required": [
                "request_verbatim",
                "success_criteria",
                "request_type"
              ],
              "properties": {
                "request_verbatim": {
                  "type": "string",
                  "x-verbatim": true,
                  "description": "The user's request exactly as they first stated it."
                },
                "success_criteria": {
                  "type": "array",
                  "items": {
                    "type": "string",
                    "x-verbatim": true
                  },
                  "minItems": 1
                },
                "request_type": {
                  "type": "string",
                  "enum": [
                    "make_a_choice",
                    "understand_whats_blocking",
                    "reassurance",
                    "meaning_or_direction",
                    "transition_or_dislocation",
                    "other"
                  ]
                },
                "feelings_mentioned": {
                  "type": "array",
                  "items": {
                    "type": "string",
                    "x-verbatim": true
                  }
                }
              }
            }
          },
          {
            "id": "restate",
            "task": "Draft alternative one-sentence restatements of the goal, each assembled only from the user's own phrases.\n",
            "model_tier": "small",
            "temperature": 0.2,
            "output_schema": {
              "type": "object",
              "required": [
                "candidates"
              ],
              "properties": {
                "candidates": {
                  "type": "array",
                  "x-candidates": true,
                  "minItems": 2,
                  "maxItems": 3,
                  "items": {
                    "type": "string"
                  }
                }
              }
            },
            "validation": [
              "Every content-bearing phrase in each candidate must appear verbatim in the transcript; connective words may be added."
            ]
          }
        ]
      },
      "confirm": {
        "present": "candidates",
        "choice_field": "restated_goal",
        "authorize_language": "This is the question we will keep returning to. You can amend it after you see your life portrait — your original wording stays saved for the final check.\n"
      },
      "artifact": {
        "schema": {
          "type": "object",
          "required": [
            "request_verbatim",
            "restated_goal",
            "success_criteria",
            "request_type"
          ],
          "properties": {
            "request_verbatim": {
              "type": "string"
            },
            "restated_goal": {
              "type": "string"
            },
            "success_criteria": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "request_type": {
              "type": "string"
            },
            "feelings_mentioned": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "amendments": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "date": {
                    "type": "string"
                  },
                  "restated_goal": {
                    "type": "string"
                  },
                  "reason": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "render": "“{{request_verbatim}}”\n→ {{restated_goal}}\nWorth it if: {{#each success_criteria}}{{this}}; {{/each}}\n"
      }
    },
    "early_recollections": {
      "id": "early_recollections",
      "version": "0.1.0",
      "kind": "conversation",
      "sector": "interview",
      "title": "Early recollections",
      "purpose": "You'll share three early memories from roughly ages three to six, name the feeling in each, and give each one a headline — like a newspaper headline, with a verb in it. The premise, from career construction theory: early memories are not history, they are the present — the stories you reach for today reveal the perspective from which you view your current transition. This is the most personal step of the whole interview. You can skip it entirely (type /skip in each topic): the perspective artifact can be inferred from your role models instead. Memories do not need to be verified facts; whatever comes to mind counts. This step only records your stories and your approved headlines; the perspective artifact is derived at the next node.\n",
      "consumes": [
        "counseling_goal"
      ],
      "invalidates": [
        "perspective"
      ],
      "elicit": {
        "persona": "Quiet, unhurried, and steady. This topic deserves the most care of the\nwhole interview. Ask one question at a time, receive each story without\ncommentary, and never rush the user.\n",
        "guardrails": [
          "This is the most personal question of the interview. Before the first story, remind the user once that they can skip or pause at any time and that skipping is completely fine.",
          "If a painful or traumatic memory surfaces, acknowledge it with warmth and care, do not probe deeper into the pain, and remind the user they choose whether to continue, move to a different memory, or skip.",
          "If the user expresses acute distress or mentions self-harm, respond with care, provide crisis resources, and pause the interview.",
          "Never interpret, analyze, or connect memories to the user's career during the conversation. Collect the stories only.",
          "Whatever the user recalls counts — fragments, images, and uncertain memories are all valid. Never question accuracy."
        ],
        "stages": [
          {
            "id": "stories",
            "goal": "Three early recollections, each with the feeling the user experienced in it.",
            "opening": "What are your earliest recollections? I'm interested in hearing three stories about things you recall happening to you when you were about three to six years old — or as early as you can remember.\n",
            "opening_i18n": {
              "ru": "Какие твои самые ранние воспоминания? Мне интересно услышать три истории о том, что случалось с тобой лет в три–шесть — или так рано, как ты только можешь вспомнить.\n"
            },
            "probes": [
              {
                "when": "only a fragment or image comes",
                "then": "Welcome it — ask them to describe the scene as they see it."
              },
              {
                "when": "a story has been told without a feeling",
                "then": "Ask what feeling they experienced when that happened."
              },
              {
                "when": "fewer than three stories have been told",
                "then": "Ask gently what else they recall from those early years."
              },
              {
                "when": "the user hesitates or goes quiet",
                "then": "Give them room — offer that they can take their time, move to a different memory, or skip."
              }
            ],
            "done_when": [
              "Three early recollections have been told.",
              "Each recollection has a feeling named by the user."
            ]
          },
          {
            "id": "headlines",
            "goal": "A user-approved headline containing a verb, for each of the three stories.",
            "opening": "Let's give each story a headline — as if it appeared in tomorrow's newspaper. What headline captures the first one? Try to include a verb.\n",
            "probes": [
              {
                "when": "the user draws a blank",
                "then": "Offer two or three headline suggestions built only from their own words, and let them adjust until one feels right."
              },
              {
                "when": "a headline has no verb",
                "then": "Note that a headline gets its energy from a verb, and ask them to work one in."
              },
              {
                "when": "a headline is settled",
                "then": "Move to the next story's headline."
              }
            ],
            "done_when": [
              "Each of the three stories has a headline the user approved.",
              "Each headline contains a verb."
            ]
          }
        ]
      },
      "induce": {
        "steps": [
          {
            "id": "extract",
            "task": "Structure the three recollections in the order told, with the feeling, the approved headline, and the headline's main verb for each.\n",
            "model_tier": "small",
            "temperature": 0.2,
            "output_schema": {
              "type": "object",
              "required": [
                "recollections"
              ],
              "properties": {
                "recollections": {
                  "type": "array",
                  "minItems": 3,
                  "maxItems": 3,
                  "items": {
                    "type": "object",
                    "required": [
                      "order",
                      "scene_phrases",
                      "feeling",
                      "headline",
                      "headline_verb"
                    ],
                    "properties": {
                      "order": {
                        "type": "integer"
                      },
                      "scene_phrases": {
                        "type": "array",
                        "minItems": 1,
                        "items": {
                          "type": "string",
                          "x-verbatim": true
                        },
                        "description": "The load-bearing phrases of the story as told."
                      },
                      "feeling": {
                        "type": "string",
                        "x-verbatim": true
                      },
                      "headline": {
                        "type": "string",
                        "description": "The wording the user approved in conversation (it may have been co-authored, so it is not checked against the user's turns alone)."
                      },
                      "headline_verb": {
                        "type": "string"
                      }
                    }
                  }
                }
              }
            },
            "validation": [
              "Each headline must be exactly the wording the user approved, and must contain a verb."
            ]
          },
          {
            "id": "salience",
            "task": "Record the first verb of the first recollection as told, and note in one sentence whether the three stories read as problem, then intensification, then resolution — or another order. No interpretation beyond that single observation.\n",
            "model_tier": "small",
            "temperature": 0.2,
            "output_schema": {
              "type": "object",
              "required": [
                "first_verb_of_first_story",
                "sequence_reading"
              ],
              "properties": {
                "first_verb_of_first_story": {
                  "type": "string",
                  "x-verbatim": true
                },
                "sequence_reading": {
                  "type": "string"
                }
              }
            }
          }
        ]
      },
      "confirm": {
        "present": "structured_review",
        "authorize_language": "These are your stories and your headlines, organized — nothing has been interpreted. Change anything that doesn't match how you told it. Your perspective artifact will be drawn only from what you approve here, and you can revisit or remove this material at any time.\n"
      },
      "artifact": {
        "schema": {
          "type": "object",
          "required": [
            "recollections",
            "first_verb_of_first_story"
          ],
          "properties": {
            "recollections": {
              "type": "array"
            },
            "first_verb_of_first_story": {
              "type": "string"
            },
            "sequence_reading": {
              "type": "string"
            }
          }
        },
        "render": "{{#each recollections}}{{order}}. “{{headline}}” — {{feeling}}\n{{/each}}\n"
      }
    },
    "favorite_media": {
      "id": "favorite_media",
      "version": "0.1.0",
      "kind": "conversation",
      "sector": "interview",
      "title": "Favorite media",
      "purpose": "You'll talk about two or three shows, sites, or magazines you keep returning to. The premise, from career construction theory: your favorite media are vicarious environments — they reveal the kinds of places, people, and problems you like to be around, which is far more trustworthy than any interest inventory. This step records your favorites and what attracts you to them, in your words. The preferred-settings artifact is derived at the next node.\n",
      "consumes": [
        "counseling_goal"
      ],
      "invalidates": [
        "preferred_settings"
      ],
      "elicit": {
        "persona": "Warm, easy curiosity — this is the lightest topic of the interview. Use the\nlanguage of interests: what do you like, enjoy, what attracts you, what do\nyou prefer. One question at a time.\n",
        "guardrails": [
          "Never judge or rank the user's taste; a soap opera reveals as much as a documentary.",
          "Never suggest what might attract the user to something — the attraction must be stated in their words.",
          "Do not interpret or classify anything during the conversation; collect only."
        ],
        "stages": [
          {
            "id": "collect",
            "goal": "Two or three favorite media the user returns to regularly.",
            "opening": "Do you watch any television programs regularly? Which ones?\n",
            "opening_i18n": {
              "ru": "Есть ли передачи или сериалы, которые ты регулярно смотришь? Какие?\n"
            },
            "probes": [
              {
                "when": "the user rarely watches television",
                "then": "Ask which websites they visit again and again."
              },
              {
                "when": "websites also draw a blank",
                "then": "Ask about magazines or podcasts they follow."
              },
              {
                "when": "only one favorite has been named",
                "then": "Ask for one or two more."
              }
            ],
            "done_when": [
              "The user has named two or three regular favorites."
            ]
          },
          {
            "id": "attractions",
            "goal": "What specifically attracts the user to each favorite.",
            "opening": "What do you like about {{item}}? What attracts you to it?\n",
            "probes": [
              {
                "when": "the user names a general-interest magazine or site",
                "then": "Ask which section they read first."
              },
              {
                "when": "the answer is vague (\"it's fun\", \"it's good\")",
                "then": "Ask what specifically they enjoy most about it."
              },
              {
                "when": "the user only summarizes the plot",
                "then": "Ask what it is about the world of that show they enjoy spending time in."
              }
            ],
            "done_when": [
              "Each named favorite has at least one attraction stated in the user's own words."
            ]
          }
        ]
      },
      "induce": {
        "steps": [
          {
            "id": "extract",
            "task": "Structure the favorites with their attractions in the order named.",
            "model_tier": "small",
            "temperature": 0.2,
            "output_schema": {
              "type": "object",
              "required": [
                "media"
              ],
              "properties": {
                "media": {
                  "type": "array",
                  "minItems": 2,
                  "items": {
                    "type": "object",
                    "required": [
                      "title",
                      "medium",
                      "attractions",
                      "named_order"
                    ],
                    "properties": {
                      "title": {
                        "type": "string"
                      },
                      "medium": {
                        "type": "string",
                        "enum": [
                          "tv",
                          "website",
                          "magazine",
                          "podcast",
                          "other"
                        ]
                      },
                      "attractions": {
                        "type": "array",
                        "minItems": 1,
                        "items": {
                          "type": "string",
                          "x-verbatim": true
                        }
                      },
                      "named_order": {
                        "type": "integer"
                      }
                    }
                  }
                }
              }
            }
          },
          {
            "id": "riasec",
            "task": "Classify each favorite's STATED ATTRACTION into the RIASEC taxonomy using only the book's definitions: R Realistic (mechanical, outdoor, making and repairing), I Investigative (scientific, analytic, solving mysteries), A Artistic (creative, aesthetic, performing), S Social (caring, conversational, educational), E Enterprising (managerial, political, persuasive), C Conventional (office, organizing, systematized). Reference examples: This Old House is R, CSI is I, America's Got Talent is A, Friends is S, Shark Tank is E, Martha Stewart is C. The code follows the user's stated attraction, never the title's genre or your own reading of the medium: a science-fiction series loved because \"the shows are imaginative\" is A, even though science fiction sounds Investigative; a magazine read for its politics sections is E, because the pull is the political world, not the act of reading or analysis. When attraction and genre disagree, the attraction wins. overall_codes are the one or two codes that dominate the stated attractions.\n",
            "model_tier": "small",
            "temperature": 0.2,
            "output_schema": {
              "type": "object",
              "required": [
                "classified",
                "overall_codes"
              ],
              "properties": {
                "classified": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "required": [
                      "title",
                      "code",
                      "rationale"
                    ],
                    "properties": {
                      "title": {
                        "type": "string"
                      },
                      "code": {
                        "type": "string",
                        "enum": [
                          "R",
                          "I",
                          "A",
                          "S",
                          "E",
                          "C"
                        ]
                      },
                      "rationale": {
                        "type": "string"
                      }
                    }
                  }
                },
                "overall_codes": {
                  "type": "array",
                  "minItems": 1,
                  "maxItems": 2,
                  "items": {
                    "type": "string",
                    "enum": [
                      "R",
                      "I",
                      "A",
                      "S",
                      "E",
                      "C"
                    ]
                  }
                }
              }
            }
          }
        ]
      },
      "confirm": {
        "present": "structured_review",
        "authorize_language": "These are your favorites and your words for what attracts you, plus a first rough setting code. Fix anything that feels off — your preferred-settings artifact will be built only from what you approve here.\n"
      },
      "artifact": {
        "schema": {
          "type": "object",
          "required": [
            "media",
            "classified",
            "overall_codes"
          ],
          "properties": {
            "media": {
              "type": "array"
            },
            "classified": {
              "type": "array"
            },
            "overall_codes": {
              "type": "array"
            }
          }
        },
        "render": "{{#each media}}• {{title}} ({{medium}}): {{#each attractions}}{{this}}; {{/each}}{{/each}}\nCodes: {{overall_codes}}\n"
      }
    },
    "favorite_story": {
      "id": "favorite_story",
      "version": "0.1.0",
      "kind": "conversation",
      "sector": "interview",
      "title": "Favorite story",
      "purpose": "You'll name your current favorite story from a book or movie and retell it in your own words. The premise, from career construction theory: the story you are drawn to right now usually carries the script for the next chapter of your own life — how a character like you deals with a predicament like yours. Your retelling is what matters, not the official plot. This step only records your version; the script artifact is derived at the next node.\n",
      "consumes": [
        "counseling_goal"
      ],
      "invalidates": [
        "script"
      ],
      "elicit": {
        "persona": "Attentive, story-loving curiosity. You want the user's version of the tale —\nthe details they keep, the ones they drop, the words they choose. One\nquestion at a time.\n",
        "guardrails": [
          "It must be the user's CURRENT favorite, not their all-time favorite — an all-time favorite usually points to a role model instead of a script.",
          "Always have the user tell the story in their own words, even if it is world-famous. Never fill in plot details for them.",
          "Do not interpret the story or connect it to their life yourself; if a bridge question is asked, the user draws the connection or declines."
        ],
        "stages": [
          {
            "id": "name",
            "goal": "One current favorite story from a book or movie.",
            "opening": "Currently, what is your favorite story from a book or movie?\n",
            "opening_i18n": {
              "ru": "Какая история из книги или фильма — твоя любимая сейчас?\n"
            },
            "probes": [
              {
                "when": "the user offers an all-time favorite from childhood",
                "then": "Honor it, then ask what story has gripped them lately — something read or watched in the last year or two."
              },
              {
                "when": "the user cannot pick one",
                "then": "Ask what book or movie they last recommended to someone."
              }
            ],
            "done_when": [
              "The user has named one current favorite story."
            ]
          },
          {
            "id": "retell",
            "goal": "The story retold in the user's own words, with a protagonist and a predicament.",
            "opening": "Tell me the story — in your own words.\n",
            "probes": [
              {
                "when": "the user says \"you probably know it\"",
                "then": "Say you want their version — the way they tell it is what matters here."
              },
              {
                "when": "the retelling is a one-liner",
                "then": "Ask what happens to the main character, and how it turns out."
              },
              {
                "when": "the retelling has no clear protagonist",
                "then": "Ask who the story is really about, for them."
              }
            ],
            "done_when": [
              "The story has been retold in the user's own words.",
              "A main character and the problem they face are identifiable from the user's telling."
            ]
          },
          {
            "id": "bridge",
            "goal": "An optional self-connection, offered once.",
            "opening": "Do you see any similarity between that story and your own situation right now?\n",
            "probes": [
              {
                "when": "the user declines or says no",
                "then": "Accept that fully and close the topic — no follow-up."
              }
            ],
            "done_when": [
              "The user has answered the bridge question once, in any way including declining."
            ]
          }
        ]
      },
      "induce": {
        "steps": [
          {
            "id": "extract",
            "task": "Structure the story exactly as the user told it.",
            "model_tier": "small",
            "temperature": 0.2,
            "output_schema": {
              "type": "object",
              "required": [
                "title",
                "medium",
                "protagonist",
                "predicament",
                "key_phrases",
                "similarity_to_self"
              ],
              "properties": {
                "title": {
                  "type": "string"
                },
                "medium": {
                  "type": "string",
                  "enum": [
                    "book",
                    "movie",
                    "tv",
                    "other"
                  ]
                },
                "protagonist": {
                  "type": "string",
                  "description": "The main character as the user framed them."
                },
                "predicament": {
                  "type": "string",
                  "description": "The central problem the character faces, per the user's telling."
                },
                "key_phrases": {
                  "type": "array",
                  "minItems": 2,
                  "items": {
                    "type": "string",
                    "x-verbatim": true
                  },
                  "description": "The load-bearing phrases of the user's retelling."
                },
                "similarity_to_self": {
                  "type": [
                    "string",
                    "null"
                  ],
                  "x-verbatim": true,
                  "description": "The user's own bridge to their situation; null if declined."
                }
              }
            }
          }
        ]
      },
      "confirm": {
        "present": "structured_review",
        "authorize_language": "This is your version of the story, structured. Fix anything that doesn't match how you told it — your script artifact will be built only from what you approve here.\n"
      },
      "artifact": {
        "schema": {
          "type": "object",
          "required": [
            "title",
            "protagonist",
            "predicament",
            "key_phrases"
          ],
          "properties": {
            "title": {
              "type": "string"
            },
            "medium": {
              "type": "string"
            },
            "protagonist": {
              "type": "string"
            },
            "predicament": {
              "type": "string"
            },
            "key_phrases": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "similarity_to_self": {
              "type": [
                "string",
                "null"
              ]
            }
          }
        },
        "render": "{{title}} — {{protagonist}}: {{predicament}}\n"
      }
    },
    "identity_statement": {
      "id": "identity_statement",
      "version": "0.1.0",
      "kind": "derived",
      "sector": "portrait",
      "title": "Identity statement",
      "purpose": "Distills your life portrait into one sentence you can carry — your success formula. The premise, from career construction theory: the future is already embedded in it. The classic template is \"I will be happy and successful when I…\", assembled from phrases of your own portrait. Several candidate formulas are drafted; you pick one, reword it, or write your own — the sentence must be one you would actually say.\n",
      "consumes": [
        "life_portrait",
        "counseling_goal"
      ],
      "invalidates": [
        "action_recipe"
      ],
      "induce": {
        "steps": [
          {
            "id": "assemble",
            "task": "From the authorized life portrait, assemble two or three alternative success formulas — single first-person sentences following the shape \"I will be happy and successful when I …\" (adapt the template naturally to the session language and to how the user speaks about themselves). Build each from the portrait's own phrases: the strongest candidates borrow the user's verbs. Each candidate should carry the career theme and point the plot forward; together they should offer a real choice of emphasis, not three wordings of one sentence.\n",
            "model_tier": "small",
            "output_schema": {
              "type": "object",
              "required": [
                "candidates",
                "source_phrases"
              ],
              "properties": {
                "candidates": {
                  "type": "array",
                  "x-candidates": true,
                  "minItems": 2,
                  "maxItems": 3,
                  "items": {
                    "type": "string"
                  }
                },
                "source_phrases": {
                  "type": "array",
                  "items": {
                    "type": "string",
                    "x-verbatim": true
                  },
                  "description": "The portrait phrases the formulas were assembled from."
                }
              }
            }
          }
        ]
      },
      "confirm": {
        "present": "candidates",
        "choice_field": "statement",
        "authorize_language": "This sentence is your compass — you'll reach for it at every confusing choice. Your action plan is built to serve it.\n"
      },
      "artifact": {
        "schema": {
          "type": "object",
          "required": [
            "statement"
          ],
          "properties": {
            "statement": {
              "type": "string"
            },
            "source_phrases": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        },
        "render": "{{statement}}\n"
      }
    },
    "life_portrait": {
      "id": "life_portrait",
      "version": "0.1.0",
      "kind": "derived",
      "sector": "portrait",
      "title": "Life portrait",
      "purpose": "Assembles everything you authorized into one large story — the life portrait. The premise, from career construction theory: the small stories you told hold together as a macronarrative with six movements, presented in a fixed order: the perspective you keep returning to, the self you built to meet it, the settings that hold you, the script you are drawn to enact, the advice you already carry, and a future scenario that answers the very request you opened with. It is written from your own words and metaphors, bends the arc hopefully without flattering, and is provisional until you authorize it — you are the author; this is a draft for your editing.\n",
      "consumes": [
        "perspective",
        "character_sketch",
        "preferred_settings",
        "script",
        "advice_to_self",
        "counseling_goal"
      ],
      "invalidates": [
        "identity_statement",
        "action_recipe"
      ],
      "induce": {
        "steps": [
          {
            "id": "compose",
            "task": "Compose the life portrait from the authorized artifacts, in six titled movements of a few sentences each, second person throughout, then join them into one continuous portrait text. Movement 1 — perspective: the \"one damn thing\" the user faces again and again, opened with feeling. Movement 2 — self: the character built to meet it, quoting the user's admired descriptor words; show, don't tell. Movement 3 — setting: the places, people, problems, and procedures that hold this self. Movement 4 — script: the storyline that unites self and setting, keeping the transformative scene visible. Movement 5 — advice: the user's motto as the direction the author-self gives the actor-self, quoted exactly. Movement 6 — future scenario: restate the user's original request, then answer it — how the career theme extends the plot in a fitting direction, turning preoccupation toward occupation. Rules: use the user's words and metaphors wherever they exist; keep tensions visible rather than smoothing them; bend the arc hopefully but never flatter; no psychological jargon, no diagnosis; the passive must turn active by the end.\n",
            "model_tier": "large",
            "output_schema": {
              "type": "object",
              "required": [
                "movements",
                "full_portrait",
                "key_quotes"
              ],
              "properties": {
                "movements": {
                  "type": "array",
                  "minItems": 6,
                  "maxItems": 6,
                  "items": {
                    "type": "object",
                    "required": [
                      "title",
                      "text"
                    ],
                    "properties": {
                      "title": {
                        "type": "string"
                      },
                      "text": {
                        "type": "string"
                      }
                    }
                  }
                },
                "full_portrait": {
                  "type": "string",
                  "description": "The six movements joined into one continuous second-person portrait."
                },
                "key_quotes": {
                  "type": "array",
                  "items": {
                    "type": "string",
                    "x-verbatim": true
                  },
                  "description": "The user's own load-bearing words woven into the portrait."
                }
              }
            }
          }
        ]
      },
      "confirm": {
        "present": "structured_review",
        "authorize_language": "This is a provisional portrait — you are its author, and it only becomes true when you say so. Rewrite freely; your success formula and action plan grow from what you approve here. Once authorized, you'll also be asked whether your original request still stands or deserves amending.\n"
      },
      "artifact": {
        "schema": {
          "type": "object",
          "required": [
            "movements",
            "full_portrait"
          ],
          "properties": {
            "movements": {
              "type": "array"
            },
            "full_portrait": {
              "type": "string"
            },
            "key_quotes": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        },
        "render": "{{full_portrait}}\n"
      },
      "gate": "all"
    },
    "motto": {
      "id": "motto",
      "version": "0.1.0",
      "kind": "conversation",
      "sector": "interview",
      "title": "Motto",
      "purpose": "You'll share your favorite saying or motto. The premise, from career construction theory: a motto is the best advice you have for yourself — condensed practical wisdom that usually states, almost verbatim, your own strategy for moving to the next chapter. At the very end of the whole journey, your motto is handed back to you. This step just records it; the advice-to-self artifact is derived at the next node.\n",
      "consumes": [
        "counseling_goal"
      ],
      "invalidates": [
        "advice_to_self"
      ],
      "elicit": {
        "persona": "Light and appreciative — this is a short topic. People often smile at this\nquestion; let them. One question at a time.\n",
        "guardrails": [
          "Any saying counts — proverb, song lyric, family phrase, something a coach once said. Never rate or improve it.",
          "If the user has no motto, composing one right now is fully valid — the book treats a saying created in the moment as equally revealing.",
          "Do not interpret the motto during the conversation; collect only."
        ],
        "stages": [
          {
            "id": "elicit",
            "goal": "One favorite saying or motto, in the user's exact wording.",
            "opening": "Tell me your favorite saying or motto.\n",
            "opening_i18n": {
              "ru": "Назови свою любимую поговорку или девиз.\n"
            },
            "probes": [
              {
                "when": "the user cannot think of one",
                "then": "Ask about a saying they remember hearing that stuck with them."
              },
              {
                "when": "still nothing comes",
                "then": "Invite them to make one up right now — the advice they would put on a card for themselves at this moment in their life."
              },
              {
                "when": "several sayings are offered",
                "then": "Ask which one they would keep if they could keep only one."
              }
            ],
            "done_when": [
              "The user has stated one saying or motto."
            ]
          },
          {
            "id": "anchor",
            "goal": "A touch of origin or context, asked once.",
            "opening": "Where does that one come from — or when does it usually come to mind?\n",
            "done_when": [
              "The user has answered once, in any way."
            ]
          }
        ]
      },
      "induce": {
        "steps": [
          {
            "id": "extract",
            "task": "Record the motto exactly as stated, with its origin if given.",
            "model_tier": "small",
            "temperature": 0.2,
            "output_schema": {
              "type": "object",
              "required": [
                "motto",
                "origin",
                "when_it_surfaces"
              ],
              "properties": {
                "motto": {
                  "type": "string",
                  "x-verbatim": true
                },
                "origin": {
                  "type": [
                    "string",
                    "null"
                  ],
                  "x-verbatim": true,
                  "description": "Where the saying comes from, in the user's words; null if not shared."
                },
                "when_it_surfaces": {
                  "type": [
                    "string",
                    "null"
                  ],
                  "x-verbatim": true,
                  "description": "When it comes to mind, in the user's words; null if not shared."
                }
              }
            }
          }
        ]
      },
      "confirm": {
        "present": "structured_review",
        "authorize_language": "This is your saying, word for word. Correct it if even one word is off — it will be repeated back to you at the end of the journey, so it should be exactly yours.\n"
      },
      "artifact": {
        "schema": {
          "type": "object",
          "required": [
            "motto"
          ],
          "properties": {
            "motto": {
              "type": "string"
            },
            "origin": {
              "type": [
                "string",
                "null"
              ]
            },
            "when_it_surfaces": {
              "type": [
                "string",
                "null"
              ]
            }
          }
        },
        "render": "“{{motto}}”\n"
      }
    },
    "perspective": {
      "id": "perspective",
      "version": "0.1.0",
      "kind": "derived",
      "sector": "induction",
      "title": "Perspective",
      "purpose": "Reads your early recollections as parables about today. The premise, from career construction theory: early memories are not history — they reveal the vantage point from which you view your current transition, and often the preoccupation your life keeps answering. The first story tends to be a précis of the present problem; the sequence often moves from problem toward resolution; your own headlines carry the leitmotifs. If you skipped early recollections, the preoccupation is inferred from your role models instead — admired courage implies familiar fear. Nothing here is a verdict: you edit and authorize every word.\n",
      "consumes": [
        "early_recollections",
        "role_models",
        "counseling_goal"
      ],
      "invalidates": [
        "character_sketch",
        "life_portrait"
      ],
      "induce": {
        "steps": [
          {
            "id": "read",
            "task": "Compose the user's perspective on their current transition from the early_recollections artifact. Treat the first recollection as a possible précis of the present problem stated in the counseling goal; weigh the first verb heavily; read the three stories as a sequence (often problem, intensification, resolution — note if the order differs); use the user's own headlines as leitmotifs and quote them exactly. Address the user in the second person. If early_recollections is absent, infer the preoccupation from the role models instead: the admired characteristics are solutions, so name the problem they solve (bravery implies fear, independence implies dependence). Never diagnose; frame everything as a perspective the user may recognize — or correct.\n",
            "model_tier": "large",
            "output_schema": {
              "type": "object",
              "required": [
                "perspective_statement",
                "preoccupation",
                "first_story_reading",
                "leitmotifs"
              ],
              "properties": {
                "perspective_statement": {
                  "type": "string",
                  "description": "Two to five second-person sentences — the vantage point from which the user views the current transition."
                },
                "preoccupation": {
                  "type": "string",
                  "description": "The recurring concern at the base of the character arc, named gently."
                },
                "first_story_reading": {
                  "type": [
                    "string",
                    "null"
                  ],
                  "description": "How the first recollection frames the present problem; null when derived from role models."
                },
                "leitmotifs": {
                  "type": "array",
                  "items": {
                    "type": "string",
                    "x-verbatim": true
                  },
                  "description": "The user's own headline words or recurring phrases."
                }
              }
            }
          }
        ]
      },
      "confirm": {
        "present": "structured_review",
        "authorize_language": "This is a perspective, not a verdict — reword anything that doesn't feel like your own view. Your character sketch and life portrait build on what you approve here.\n"
      },
      "artifact": {
        "schema": {
          "type": "object",
          "required": [
            "perspective_statement",
            "preoccupation"
          ],
          "properties": {
            "perspective_statement": {
              "type": "string"
            },
            "preoccupation": {
              "type": "string"
            },
            "first_story_reading": {
              "type": [
                "string",
                "null"
              ]
            },
            "leitmotifs": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        },
        "render": "{{perspective_statement}}\n"
      }
    },
    "preferred_settings": {
      "id": "preferred_settings",
      "version": "0.1.0",
      "kind": "derived",
      "sector": "induction",
      "title": "Preferred settings",
      "purpose": "Turns your favorite media into a picture of where you like to be. The premise, from career construction theory: favorite shows, sites, and magazines are vicarious environments — trustworthy evidence of the settings you seek. They are analyzed along four dimensions: places, people, problems, and procedures, and summarized in the Holland (RIASEC) vocabulary. This is a description of attraction, not a prescription of jobs — occupations come later, and you authorize everything.\n",
      "consumes": [
        "favorite_media",
        "counseling_goal"
      ],
      "invalidates": [
        "script",
        "life_portrait"
      ],
      "induce": {
        "steps": [
          {
            "id": "analyze",
            "task": "From the favorite_media artifact, describe the user's preferred occupational settings along the book's four dimensions — the places they want to be in, the people they want around them, the problems they prefer to address, and the procedures they like to use. Ground every dimension in the user's stated attractions and quote their words where they carry the meaning. Confirm or refine the RIASEC codes from the media artifact, basing each code on the stated attraction rather than the title. Assign only the one or two dominant codes the attractions clearly express: never infer an additional code from intellectual tone, from analysis-flavored language in your own descriptions, or from the user's current studies, abilities, or achievements — attraction is the only evidence that counts. Close with a short second-person niche statement — the kind of stage on which this user can perform themselves.\n",
            "model_tier": "small",
            "output_schema": {
              "type": "object",
              "required": [
                "places",
                "people",
                "problems",
                "procedures",
                "riasec",
                "niche_statement"
              ],
              "properties": {
                "places": {
                  "type": "string"
                },
                "people": {
                  "type": "string"
                },
                "problems": {
                  "type": "string"
                },
                "procedures": {
                  "type": "string"
                },
                "riasec": {
                  "type": "object",
                  "required": [
                    "codes",
                    "rationale"
                  ],
                  "properties": {
                    "codes": {
                      "type": "array",
                      "minItems": 1,
                      "maxItems": 2,
                      "items": {
                        "type": "string",
                        "enum": [
                          "R",
                          "I",
                          "A",
                          "S",
                          "E",
                          "C"
                        ]
                      }
                    },
                    "rationale": {
                      "type": "string"
                    }
                  }
                },
                "niche_statement": {
                  "type": "string",
                  "description": "Two or three second-person sentences describing the setting that would hold this user well."
                },
                "evidence": {
                  "type": "array",
                  "items": {
                    "type": "string",
                    "x-verbatim": true
                  },
                  "description": "The user's own attraction phrases that carry this reading — each entry must be the bare quote exactly as the user said it, with no framing text of yours around it."
                }
              }
            }
          }
        ]
      },
      "confirm": {
        "present": "structured_review",
        "authorize_language": "This describes where you're drawn, in your own evidence — correct anything that doesn't ring true. Your script and life portrait build on what you approve here.\n"
      },
      "artifact": {
        "schema": {
          "type": "object",
          "required": [
            "places",
            "people",
            "problems",
            "procedures",
            "riasec",
            "niche_statement"
          ],
          "properties": {
            "places": {
              "type": "string"
            },
            "people": {
              "type": "string"
            },
            "problems": {
              "type": "string"
            },
            "procedures": {
              "type": "string"
            },
            "riasec": {
              "type": "object"
            },
            "niche_statement": {
              "type": "string"
            },
            "evidence": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        },
        "render": "{{niche_statement}}\n"
      }
    },
    "role_models": {
      "id": "role_models",
      "version": "0.1.0",
      "kind": "conversation",
      "sector": "interview",
      "title": "Role models",
      "purpose": "You'll talk about three figures you admired when you were around six years old. The premise, from career construction theory: the traits you say you admired are the blueprint you used to build yourself — it is what you admired, not whom, that matters. This step only records and organizes your own words. The character sketch is drafted at the next node, from what you approve here, and shown for your approval too.\n",
      "consumes": [
        "counseling_goal"
      ],
      "invalidates": [
        "character_sketch"
      ],
      "elicit": {
        "persona": "You are a career construction interviewer. Warm, playful curiosity; one\nquestion at a time. You care about what the user admired, never about whom.\nYour follow-ups voice inferences, not interpretations — thought-provoking,\noccasionally humorous, always offered so the user can correct them.\n",
        "guardrails": [
          "Never suggest characteristics or admire-worthy traits yourself. Every descriptor must originate from the user.",
          "Never assume what a famous figure \"obviously\" stands for. One person admires Superman for truth and justice; another admired only his invisible airplane. Always ask what specifically this user admired.",
          "Fictional characters, cartoon figures, and animal characters are fully valid role models — welcome them without surprise.",
          "Parents named as models are recorded as guides, not models. Honor the parent, then ask for someone besides their parents. If the user expresses a collectivist orientation where family expectations weigh heavily, note parental influences with extra care rather than pushing past them.",
          "If a painful memory surfaces, acknowledge it with care, do not probe it here, and remind the user they can skip or pause at any time."
        ],
        "stages": [
          {
            "id": "collect",
            "goal": "Three admired figures from around age six, none of them parents.",
            "opening": "Who did you admire when you were about six years old? Tell me about her or him.\n",
            "opening_i18n": {
              "ru": "Кто был твоим кумиром, когда тебе было лет шесть? Расскажи мне о нём — или о ней.\n"
            },
            "probes": [
              {
                "when": "the user can't think of anyone",
                "then": "Suggest the model need not be famous — a relative, neighbor, teacher, or a character from a book, cartoon, or show all count."
              },
              {
                "when": "the user names a parent",
                "then": "Ask what the parent was like and record those qualities as guide descriptors, then ask whom they admired besides their parents."
              },
              {
                "when": "fewer than three models have been named",
                "then": "Ask for another — \"Who else did you admire back then?\""
              }
            ],
            "done_when": [
              "Three non-parent models have been named."
            ]
          },
          {
            "id": "describe",
            "goal": "At least two descriptor phrases per model, as seen through childhood eyes.",
            "opening": "Describe {{model}} to me. Just tell me about them as you viewed them back then — what were they like?\n",
            "probes": [
              {
                "when": "the user describes what the model did (actions, plot, feats)",
                "then": "Ask what the model was like — their characteristics."
              },
              {
                "when": "the user describes the model as they see them today",
                "then": "Ask how they viewed the model when they were young, and what first drew them to the model."
              },
              {
                "when": "descriptors stay sparse after asking",
                "then": "Ask what specifically they admired about this one."
              },
              {
                "when": "a descriptor invites an obvious inference",
                "then": "Offer it as a playful question they can correct — someone who admires Zorro might be asked, \"Do you mask your true identity? Do you seek to right wrongs?\""
              }
            ],
            "done_when": [
              "Each of the three models has at least two descriptor phrases."
            ]
          },
          {
            "id": "compare",
            "goal": "Similarities and differences between the user and each model.",
            "opening": "How are you similar to {{model}} — and how are you different?\n",
            "probes": [
              {
                "when": "all three models have been compared",
                "then": "Optionally ask what all three have in common."
              }
            ],
            "done_when": [
              "A similarity or difference has been noted for each model."
            ]
          }
        ]
      },
      "induce": {
        "steps": [
          {
            "id": "extract",
            "task": "Structure the models and guides with descriptors in the order spoken.",
            "model_tier": "small",
            "temperature": 0.2,
            "output_schema": {
              "type": "object",
              "required": [
                "models"
              ],
              "properties": {
                "models": {
                  "type": "array",
                  "minItems": 3,
                  "maxItems": 3,
                  "items": {
                    "type": "object",
                    "required": [
                      "name",
                      "named_order",
                      "descriptors"
                    ],
                    "properties": {
                      "name": {
                        "type": "string"
                      },
                      "named_order": {
                        "type": "integer"
                      },
                      "descriptors": {
                        "type": "array",
                        "minItems": 2,
                        "items": {
                          "type": "object",
                          "properties": {
                            "text": {
                              "type": "string",
                              "x-verbatim": true
                            },
                            "spoken_order": {
                              "type": "integer"
                            }
                          }
                        }
                      },
                      "similarities": {
                        "type": "array",
                        "items": {
                          "type": "string",
                          "x-verbatim": true
                        }
                      },
                      "differences": {
                        "type": "array",
                        "items": {
                          "type": "string",
                          "x-verbatim": true
                        }
                      }
                    }
                  }
                },
                "guides": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "name": {
                        "type": "string"
                      },
                      "relationship": {
                        "type": "string"
                      },
                      "descriptors": {
                        "type": "array",
                        "items": {
                          "type": "string",
                          "x-verbatim": true
                        }
                      }
                    }
                  }
                },
                "shared_by_all": {
                  "type": [
                    "string",
                    "null"
                  ],
                  "x-verbatim": true,
                  "description": "Null if the user was not asked or had no answer."
                }
              }
            }
          },
          {
            "id": "salience",
            "task": "Mark salient self-conceptions by primacy and repetition. Primacy: the first descriptor of the first-named model. Repetition: descriptors repeated or closely echoed across models.\n",
            "model_tier": "small",
            "temperature": 0.2,
            "output_schema": {
              "type": "object",
              "required": [
                "primacy_trait",
                "repeated_traits"
              ],
              "properties": {
                "primacy_trait": {
                  "type": "string",
                  "x-verbatim": true
                },
                "repeated_traits": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "trait": {
                        "type": "string"
                      },
                      "echoes": {
                        "type": "array",
                        "minItems": 2,
                        "items": {
                          "type": "string",
                          "x-verbatim": true
                        }
                      }
                    }
                  }
                }
              }
            },
            "validation": [
              "primacy_trait must equal the first spoken descriptor of the model with named_order 1.",
              "Each repeated_traits entry must cite echoes from at least two different models."
            ]
          }
        ]
      },
      "confirm": {
        "present": "structured_review",
        "authorize_language": "These are your words, organized. Fix anything that doesn't sound like you — your character sketch will be built only from what you approve here.\n"
      },
      "artifact": {
        "schema": {
          "type": "object",
          "required": [
            "models",
            "primacy_trait",
            "repeated_traits"
          ],
          "properties": {
            "models": {
              "type": "array"
            },
            "guides": {
              "type": "array"
            },
            "shared_by_all": {
              "type": "string"
            },
            "primacy_trait": {
              "type": "string"
            },
            "repeated_traits": {
              "type": "array"
            }
          }
        },
        "render": "{{#each models}}• {{name}}: {{#each descriptors}}{{text}}, {{/each}}{{/each}}\nFirst said: “{{primacy_trait}}” — repeated: {{#each repeated_traits}}{{trait}}; {{/each}}\n"
      }
    },
    "script": {
      "id": "script",
      "version": "0.1.0",
      "kind": "derived",
      "sector": "induction",
      "title": "Script",
      "purpose": "Finds the storyline in your favorite story. The premise, from career construction theory: your current favorite story carries the script for the next chapter — a character like you, facing a predicament like yours, and a way through it. The script unites your self (character sketch) with your setting (preferred settings). One duty of care from the book: favorite stories are cultural products, so any limiting assumptions hiding in the script are flagged for your own critical eye — the story is an invitation, never a prescription. You edit and authorize everything.\n",
      "consumes": [
        "favorite_story",
        "character_sketch",
        "preferred_settings",
        "counseling_goal"
      ],
      "invalidates": [
        "life_portrait"
      ],
      "induce": {
        "steps": [
          {
            "id": "compose",
            "task": "From the favorite_story artifact — as the user retold it, using their key phrases — articulate the script for the user's next chapter: how a self like theirs (character_sketch) meets a setting like theirs (preferred_settings) and moves through a predicament like the one in the story. Address the user in the second person. Name the transformative scene — the moment in their telling where the turn happens — and state the credo the story carries (the idea a life like this serves). Then, gently and briefly, note anything in the script that could confine rather than free the user (gender expectations, prescribed endings, borrowed obligations) as questions for the user to judge, not corrections. Trace how the script turns passive into active. Never invent plot the user did not tell.\n",
            "model_tier": "large",
            "output_schema": {
              "type": "object",
              "required": [
                "script_statement",
                "transformative_scene",
                "credo",
                "passive_to_active"
              ],
              "properties": {
                "script_statement": {
                  "type": "string",
                  "description": "Three to six second-person sentences — the storyline for the next chapter."
                },
                "transformative_scene": {
                  "type": "string"
                },
                "credo": {
                  "type": "string",
                  "description": "The idea served by a life following this script."
                },
                "passive_to_active": {
                  "type": "string",
                  "description": "One sentence — from being influenced by the problem to influencing it."
                },
                "deconstruction_notes": {
                  "type": [
                    "string",
                    "null"
                  ],
                  "description": "Possible confining assumptions in the story, framed as open questions; null if none stand out."
                },
                "story_phrases": {
                  "type": "array",
                  "items": {
                    "type": "string",
                    "x-verbatim": true
                  },
                  "description": "The user's own phrases from the retelling that carry the script."
                }
              }
            }
          }
        ]
      },
      "confirm": {
        "present": "structured_review",
        "authorize_language": "A script is an invitation, not a prescription — rewrite anything that doesn't feel like your storyline. The life portrait builds on what you approve here.\n"
      },
      "artifact": {
        "schema": {
          "type": "object",
          "required": [
            "script_statement",
            "transformative_scene",
            "credo"
          ],
          "properties": {
            "script_statement": {
              "type": "string"
            },
            "transformative_scene": {
              "type": "string"
            },
            "credo": {
              "type": "string"
            },
            "passive_to_active": {
              "type": "string"
            },
            "deconstruction_notes": {
              "type": [
                "string",
                "null"
              ]
            },
            "story_phrases": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        },
        "render": "{{script_statement}}\n"
      }
    }
  } as unknown as Record<string, Playbook>;
